#!/bin/bash
$LIBPATH=/usr/lib/gcc/arm-none-eabi/6.3.1/
# 1. What does the following statement do?
#	- Assembles ts.s into ts.o, setting flags for debugging
arm-none-eabi-as -mcpu=arm926ej-s -g ts.s -o ts.o

# 2. What does the following statement do?
#	- Compiles t.c into t.o w/ flags
arm-none-eabi-gcc -c -mcpu=arm926ej-s -g t.c -o t.o

# 3. What does the following statement do?
#	- Links the files to create t.elf
#arm-none-eabi-ld -T t.ld ts.o t.o -o t.elf

arm-none-eabi-ld -T t.ld -L $LIBPATH ts.o t.o -o t.elf -lgcc -lstr

# 4. What does the following statement do?
#	- Creates a binary executable from t.elf
arm-none-eabi-objcopy -O binary t.elf t.bin

rm *.o *.elf

echo ready to go?
read dummy

qemu-system-arm -M versatilepb -m 128M -kernel t.bin \
-serial mon:stdio
